name: AMR-Flow CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          wget -qO- https://get.nextflow.io | bash
          chmod +x nextflow
          sudo mv nextflow /usr/local/bin/
          pip install streamlit boto3 pandas

      # Run Nextflow from the 'nextflow' directory
      - name: Run Nextflow Test Profile
        run: |
          nextflow run nextflow/main.nf -profile test

      # Smoke Test Streamlit from the 'ui' directory
      - name: Streamlit Smoke Test
        run: |
          nohup streamlit run ui/app.py & 
          sleep 10
          pkill -f streamlit
